### ISSUE TITLE
RestClientBL.java - Change class name

### ISSUE THREAD

**Issue by suvonkar** [ES-KOL-SCM-GIT/RallyInspector#10]
As we have planned to write business logic in separate class for each discrepancy then the class name should reflect that.

Please change the class name.

**Comment by sayan72902** [comment]
Class name changed to UserStoryWithoutFeatureQuery, to reflect the discrepancy for which query is being written. This class is in a separate package. All subsequent query creating classes will be written here.

**Comment by suvonkar** [comment]
Addressed...
