### ISSUE TITLE
DiscrepancyReportPopulator.java - Class name or method name is more generic

### ISSUE THREAD

**Issue by suvonkar** [ES-KOL-SCM-GIT/RallyInspector#16]
Please give a proper class or method name to specify that it populates the JSON Object for discrepancy 1.

**Comment by sayan72902** [comment]
Renamed class to StoryWithoutFeatureDiscrepancyReportPopulator

**Comment by suvonkar** [comment]
Why we need a separate class to write a method called `createDiscrepancyTablePopulator`, to populate a JSON Object to save in DB. Instead of we can write a private method in UserStoryWithoutFeatureQuery class. Please think about it.

**Comment by sayan72902** [comment]
Addressed this issue. The Discrepancy Table populator is now created inside the same class where all the other business logic is handled. The business logic class has been renamed to <Specific Discrepancy Name>DiscrepancyHandler. This is the convention that will be followed for all other discrepancy handler classes.

**Comment by suvonkar** [comment]
Addressed...
