### ISSUE TITLE
UserStoryWithoutFeatureQuery.java - createQueryForPost method name is misleading

### ISSUE THREAD

**Issue by suvonkar** [ES-KOL-SCM-GIT/RallyInspector#19]
Inside the method we are preparing the query as well as we are calling the Rally. But the method name is createQueryForPost, which is misleading.

Give a proper method name.

**Comment by sayan72902** [comment]
Renamed method to createStoryWithoutFeatureQuery().

**Comment by suvonkar** [comment]
Reviewed..

But please check the comment of the below issue.

https://github.com/sayan72902/RallyInspector/issues/16

**Comment by sayan72902** [comment]
Incorporated issue #16.

**Comment by suvonkar** [comment]
Addressed...
