### ISSUE TITLE
Move local static variable to property file for RestClientConnector.java

### ISSUE THREAD

**Issue by suvonkar** [ES-KOL-SCM-GIT/RallyInspector#2]
Move local static variable to property file.

SERVER_URI , CHECK_QUERY_FILTER , QUERY_RALLY

**Comment by sayan72902** [comment]
Moved all static variables to property file "application.properties". Changed the name of the class to RallyInspectorConnector, in accordance with function.

**Comment by suvonkar** [comment]
Ok
