### ISSUE TITLE
Method / Class Commenting

### ISSUE THREAD

**Issue by suvonkar** [ES-KOL-SCM-GIT/RallyInspector#21]
Please follow the below URL for method/class commenting.

http://www2.hawaii.edu/~tp_200/ics111/material/codingStandards.html

http://www.oracle.com/technetwork/articles/java/index-137868.html

**Comment by sayan72902** [comment]
Addressed comments in the way shown in the second document. Please have a look.

**Comment by suvonkar** [comment]
Addressed...
