### ISSUE TITLE
UserStoryWithoutFeatureDiscrepancyHandler.java - Please make the method as private

### ISSUE THREAD

**Issue by suvonkar** [ES-KOL-SCM-GIT/RallyInspector#22]
Please make the following method as private as it has no outside use.

invokeStoryWithoutFeatureQuery,
insertDiscrepanciesIntoDB,
createDiscrepancyTablePopulator

**Comment by sayan72902** [comment]
Said methods have been marked as private.

**Comment by suvonkar** [comment]
Addressed...
