### ISSUE TITLE
RestClientConnector.java - change the method name firePostRequest

### ISSUE THREAD

**Issue by suvonkar** [ES-KOL-SCM-GIT/RallyInspector#3]
Please change the method name of firePostRequest like postData

**Comment by sayan72902** [comment]
Method name changed

**Comment by suvonkar** [comment]
As the connector is generic so method name should not contain **_"RallyQuery"**_.

```
postRallyQueryData
```

**Comment by sayan72902** [comment]
Method name changed to postData in accordance with comments

**Comment by suvonkar** [comment]
Addressed...
