### ISSUE TITLE
RestClientConnector.java  - Don't hard code the webResource type as JSON

### ISSUE THREAD

**Issue by suvonkar** [ES-KOL-SCM-GIT/RallyInspector#4]
Don't hard code the webResource type as JSON. Take it as a method parameter. Whihc will make it configurable by caller.

**Comment by sayan72902** [comment]
Hard-coded data shifted to application.properties file

**Comment by suvonkar** [comment]
Hard code is removed but still I am not getting any **_application.properties**_ file in Git

**Comment by sayan72902** [comment]
Property file structure in place for reading values from application.properties. Will be Githubbed by EOD today.

**Comment by suvonkar** [comment]
Addressed...
