### ISSUE TITLE
RestClientConnector.java - Don't use ghost number like 200

### ISSUE THREAD

**Issue by suvonkar** [ES-KOL-SCM-GIT/RallyInspector#5]
Please Don't use ghost number like 200. Use Httpsstatus enum.

**Comment by sayan72902** [comment]
Hard-coded number removed. All such data are now read from application.properties.

**Comment by suvonkar** [comment]
Hard code is removed but still I am not getting any **_application.properties**_ file in Git

**Comment by sayan72902** [comment]
Property file structure in place for reading values from application.properties

**Comment by suvonkar** [comment]
Addressed...
