### ISSUE TITLE
Replace the duplicate JSON conversion

### ISSUE THREAD

**Issue by suvonkar** [ES-KOL-SCM-GIT/RallyInspector#8]
``` java
        String result = response.getEntity(String.class);
        try {
            JSONObject resultJsonObject = new JSONObject(result);
        ......
```

In the above code is fetching the response as String and then transferring it into JSON. Please replace this duplicate conversion and fetch the JSON in one step.

**Comment by sayan72902** [comment]
Retrieved JSON directly stored in JSONObject instance

**Comment by suvonkar** [comment]
Addressed...
